version: "3.9"

services:
  web:
    container_name: web-server
    build:
      context: ./web
      dockerfile: Dockerfile.web1
    networks: 
      - web-service
    ports: 
      - "3000:3000"
    environment:
      - DD_ENV=development
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DATADOG_HOST=datadog
    labels:
      com.datadoghq.tags.env: 'development'
      com.datadog.tags.service: 'datadog-playground'
      com.datadoghq.tags.version: '1.0.0'
  web2:
    container_name: web2-server
    build:
      context: ./web
      dockerfile: Dockerfile.web2
    networks:
      - web-service
    environment:
      - DD_ENV=development
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DATADOG_HOST=datadog 
    labels:
      com.datadoghq.tags.env: 'development'
      com.datadog.tags.service: 'datadog-playground-2'
      com.datadoghq.tags.version: '1.0.0'
 
  datadoghq:
    container_name: datadog-agent
    image: 'gcr.io/datadoghq/agent:latest'
    pid: host
    networks:
      - web-service
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_SITE=datadoghq.com
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true
      - 'DD_CONTAINER_EXCLUDE=name:datadog-agent'
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
      - '/sys/kernel/debug:/sys/kernel/debug'
networks:
  web-service:
