version: "3.9"

services:
  dd-toy:
    container_name: dd-toy
    build:
      context: ./web
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - dd-toy
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DATADOG_HOST=datadog
    labels:
      com.datadoghq.ad.logs: '[{"source": "docker-container", "service": "dd-toy"}]'
  
  datadoghq:
    container_name: datadog-agent
    image: 'gcr.io/datadoghq/agent:latest'
    pid: host
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_SITE=datadoghq.com
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true
      - 'DD_CONTAINER_EXCLUDE=name:datadog-agent'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
networks:
  dd-toy:
