# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

COPY *.go ./

RUN go mod download
RUN go mod tidy

RUN go build -o datadog_playground_2

EXPOSE 3001

CMD [ "./datadog_playground_2" ]
