# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

COPY . ./

RUN go mod download
RUN go mod tidy

RUN go build -o web1 ./cmd/web1/main.go

EXPOSE 3000

CMD [ "./web1" ]
