# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

COPY . ./

RUN go mod download
RUN go mod tidy

RUN go build -o web2 ./cmd/web2/main.go

EXPOSE 3001

CMD [ "./web2" ]
