# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

COPY *.go ./

RUN go mod download
RUN go mod tidy

RUN go build -o dd-toy

EXPOSE 3000

CMD [ "./dd-toy" ]
